# -*- coding: utf-8 -*-
"""Techhome_bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r83RMBol6Nf4b5xcGWsZkUCp_8bOEQbd
"""

pip install python-telegram-bot gspread oauth2client

import random
from datetime import datetime
import smtplib
from email.mime.text import MIMEText

import nest_asyncio
nest_asyncio.apply()

import gspread
from oauth2client.service_account import ServiceAccountCredentials

from telegram import Update, ReplyKeyboardMarkup
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    filters
)

TOKEN = os.environ.get("TOKEN")
EMAIL = os.environ.get("EMAIL")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")

SHEET_ID = os.environ.get("SHEET_ID")
CREDENTIALS_FILE = os.environ.get("CREDENTIALS_FILE")

scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive"
]creds = ServiceAccountCredentials.from_json_keyfile_name(
    CREDENTIALS_FILE, scope
)

client = gspread.authorize(creds)
sheet = client.open_by_key(SHEET_ID).sheet1

menu = ReplyKeyboardMarkup(
    [
        ["🛠 Servicio técnico", "💰 Cotización"],
        ["📩 PQRS"],
        ["🔎 Consultar ticket"]
    ],
    resize_keyboard=True
)

menu_servicio = ReplyKeyboardMarkup(
    [
        ["Gasodoméstico", "Electrodoméstico"],
        ["Cámaras", "Otro"]
    ],
    resize_keyboard=True
)

menu_pqrs = ReplyKeyboardMarkup(
    [
        ["Garantía", "Reclamo"]
    ],
    resize_keyboard=True
)

def generar_id():
    return f"TECH-{random.randint(1000,9999)}"

def enviar_correo(asunto, cuerpo):
    msg = MIMEText(cuerpo)
    msg["Subject"] = asunto
    msg["From"] = EMAIL
    msg["To"] = EMAIL

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(EMAIL, EMAIL_PASSWORD)
        server.send_message(msg)

def guardar_ticket(fila):
    sheet.append_row(fila)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    # limpiar cualquier estado previo
    context.user_data.clear()
    context.user_data["step"] = None

    await update.message.reply_text(
        "👋 Bienvenido a TECHHOME\n\n"
        "🧠 Sistema de gestión de solicitudes técnicas\n"
        "📊 Registro automático de tickets\n\n"
        "👉 Por favor selecciona una opción del menú inferior:",
        reply_markup=menu
    )

async def handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text.lower()

    # =========================
    # BIENVENIDA AUTOMÁTICA
    # =========================
    if text in ["hola", "buenos dias", "buenas tardes", "buenas noches", "hey", "hello"]:
        context.user_data.clear()

        await update.message.reply_text(
            "👋 Bienvenido a TECHHOME\n\n"
            "🧠 Sistema de gestión de solicitudes técnicas\n"
            "📊 Registro y seguimiento de tickets\n\n"
            "👉 Selecciona una opción del menú:",
            reply_markup=menu
        )
        return

    # =========================
    # INICIO CONSULTA TICKET
    # =========================
    if text == "🔎 consultar ticket":
        context.user_data.clear()
        context.user_data["consultando_ticket"] = True

        await update.message.reply_text(
            "🔎 Escribe tu número de ticket:\n\nEjemplo: TECH-1234"
        )
        return

    # =========================
    # BUSQUEDA DE TICKET
    # =========================
    if context.user_data.get("consultando_ticket"):

        ticket_id = text.strip().upper()

        registros = sheet.get_all_records()

        for row in registros:
            if str(row["TICKET ID"]).upper() == ticket_id:

                estado = row["ESTADO"]

                estado_msg = {
                    "Abierto": "🟡 Recibido y en cola",
                    "En proceso": "🔧 Técnico asignado",
                    "En visita": "🚗 En camino / atendiendo",
                    "Resuelto": "✅ Reparación finalizada",
                    "Cerrado": "🏁 Caso finalizado"
                }.get(estado, estado)

                await update.message.reply_text(
                    f"""🔎 INFORMACIÓN DEL TICKET

📌 ID: {row['TICKET ID']}
📅 Fecha: {row['FECHA']}
👤 Cliente: {row['NOMBRE']}
📞 Tel: {row['TELEFONO']}

Tipo: {row['TIPO']}
Subtipo: {row['SUBTIPO']}

Estado: {estado_msg}

📝 Descripción:
{row['DESCRIPCION']}

🤖 TECHHOME te mantendrá informado."""
                )

                context.user_data["consultando_ticket"] = False
                return

        await update.message.reply_text(
            "❌ No encontramos ese ticket.\nVerifica el ID e intenta nuevamente."
        )

        context.user_data["consultando_ticket"] = False
        return

    # =========================
    # SERVICIO TECNICO
    # =========================
    if text == "🛠 servicio técnico":
        context.user_data.clear()
        context.user_data["flow"] = "servicio"

        await update.message.reply_text(
            "🔧 ¿Qué tipo de equipo es?",
            reply_markup=menu_servicio
        )
        return

    if text in ["gasodoméstico", "electrodoméstico", "cámaras", "otro"]:
        context.user_data["subtipo"] = text
        await update.message.reply_text("📝 Describe el problema:")
        return

    # =========================
    # COTIZACION
    # =========================
    if text == "💰 cotización":
        context.user_data.clear()
        context.user_data["flow"] = "cotizacion"

        await update.message.reply_text(
            "📝 Describe el daño o mantenimiento:"
        )
        return

    # =========================
    # PQRS
    # =========================
    if text == "📩 pqrs":
        context.user_data.clear()
        context.user_data["flow"] = "pqrs"

        await update.message.reply_text(
            "📌 ¿Es Garantía o Reclamo?",
            reply_markup=menu_pqrs
        )
        return

    if text in ["garantía", "reclamo"]:
        context.user_data["subtipo"] = text
        await update.message.reply_text("📝 Describe tu solicitud:")
        return

    # =========================
    # FLUJO GENERAL (CREACIÓN TICKET)
    # =========================
    if "descripcion" not in context.user_data:
        context.user_data["descripcion"] = text
        await update.message.reply_text("👤 Nombre del cliente:")
        return

    if "nombre" not in context.user_data:
        context.user_data["nombre"] = text
        await update.message.reply_text("📞 Teléfono:")
        return

    if "telefono" not in context.user_data:
        context.user_data["telefono"] = text

        ticket_id = generar_id()
        fecha = datetime.now().strftime("%Y-%m-%d %H:%M")

        fila = [
            ticket_id,
            fecha,
            context.user_data.get("nombre"),
            context.user_data.get("telefono"),
            context.user_data.get("flow"),
            context.user_data.get("subtipo"),
            context.user_data.get("descripcion"),
            "Abierto"
        ]

        guardar_ticket(fila)

        correo = f"""
📌 NUEVO TICKET TECHHOME

ID: {ticket_id}
Fecha: {fecha}

Cliente: {context.user_data.get('nombre')}
Tel: {context.user_data.get('telefono')}

Tipo: {context.user_data.get('flow')}
Subtipo: {context.user_data.get('subtipo')}

Descripción:
{context.user_data.get('descripcion')}

Estado: Abierto

Un asesor se comunicará pronto.
"""

        enviar_correo(f"Ticket TECHHOME {ticket_id}", correo)

        await update.message.reply_text(
            f"✅ Ticket creado: {ticket_id}\n📞 Te contactaremos pronto.",
            reply_markup=menu
        )

        context.user_data.clear()
        return

app = ApplicationBuilder().token(TOKEN).build()

app.add_handler(CommandHandler("start", start))
app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handler))

async def main():
    await app.initialize()
    await app.start()
    print("🤖 TECHHOME BOT ACTIVO")
    await app.updater.start_polling()

await main()
